
-- ================================
-- Hospital Database - DDL
-- Oracle Style
-- ================================

CREATE TABLE patients (
    patient_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    national_id   VARCHAR2(30),
    full_name     VARCHAR2(200) NOT NULL,
    date_of_birth DATE,
    gender        VARCHAR2(10),
    phone_number  VARCHAR2(30),
    email         VARCHAR2(100),
    CONSTRAINT pk_patients PRIMARY KEY (patient_id)
);

CREATE TABLE departments (
    department_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL,
    floor_number    NUMBER,
    CONSTRAINT pk_departments PRIMARY KEY (department_id)
);

CREATE TABLE doctors (
    doctor_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name       VARCHAR2(200) NOT NULL,
    specialty       VARCHAR2(100),
    license_number  VARCHAR2(50),
    department_id   NUMBER,
    hire_date       DATE,
    CONSTRAINT pk_doctors PRIMARY KEY (doctor_id),
    CONSTRAINT fk_doctors_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE nurses (
    nurse_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    full_name       VARCHAR2(200) NOT NULL,
    department_id   NUMBER,
    shift_type      VARCHAR2(30),
    CONSTRAINT pk_nurses PRIMARY KEY (nurse_id),
    CONSTRAINT fk_nurses_department
        FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

CREATE TABLE rooms (
    room_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    room_number VARCHAR2(20) NOT NULL,
    room_type   VARCHAR2(50),
    capacity    NUMBER,
    CONSTRAINT pk_rooms PRIMARY KEY (room_id)
);

CREATE TABLE admissions (
    admission_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id     NUMBER NOT NULL,
    room_id        NUMBER,
    admission_date DATE NOT NULL,
    discharge_date DATE,
    CONSTRAINT pk_admissions PRIMARY KEY (admission_id),
    CONSTRAINT fk_adm_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    CONSTRAINT fk_adm_room FOREIGN KEY (room_id) REFERENCES rooms(room_id)
);

CREATE TABLE appointments (
    appointment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    appointment_date DATE NOT NULL,
    status           VARCHAR2(30),
    CONSTRAINT pk_appointments PRIMARY KEY (appointment_id),
    CONSTRAINT fk_app_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    CONSTRAINT fk_app_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
);

CREATE TABLE medical_records (
    record_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id  NUMBER NOT NULL,
    diagnosis   VARCHAR2(400),
    notes       VARCHAR2(2000),
    created_at  DATE DEFAULT SYSDATE,
    CONSTRAINT pk_medical_records PRIMARY KEY (record_id),
    CONSTRAINT fk_mr_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id)
);

CREATE TABLE prescriptions (
    prescription_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    patient_id      NUMBER NOT NULL,
    doctor_id       NUMBER NOT NULL,
    medication_name VARCHAR2(200),
    dosage          VARCHAR2(100),
    CONSTRAINT pk_prescriptions PRIMARY KEY (prescription_id),
    CONSTRAINT fk_pr_patient FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    CONSTRAINT fk_pr_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
);

CREATE TABLE inventory_items (
    item_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    item_name       VARCHAR2(200) NOT NULL,
    item_category   VARCHAR2(100),
    unit_of_measure VARCHAR2(50),
    reorder_level   NUMBER,
    CONSTRAINT pk_inventory_items PRIMARY KEY (item_id)
);

CREATE TABLE inventory_stock (
    stock_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    item_id          NUMBER NOT NULL,
    location         VARCHAR2(100),
    quantity_on_hand NUMBER,
    expiration_date  DATE,
    CONSTRAINT pk_inventory_stock PRIMARY KEY (stock_id),
    CONSTRAINT fk_stock_item FOREIGN KEY (item_id) REFERENCES inventory_items(item_id)
);

CREATE TABLE suppliers (
    supplier_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_name VARCHAR2(200) NOT NULL,
    contact_info  VARCHAR2(300),
    CONSTRAINT pk_suppliers PRIMARY KEY (supplier_id)
);
