CREATE USER hospitalerp IDENTIFIED BY hospitalerp
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO hospitalerp;
GRANT CREATE TABLE TO hospitalerp;
GRANT CREATE SEQUENCE TO hospitalerp;
GRANT CREATE VIEW TO hospitalerp;
GRANT CREATE PROCEDURE TO hospitalerp;
GRANT CREATE TRIGGER TO hospitalerp;
